
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ferec
 */
public class OrderApp extends javax.swing.JFrame {
    Map<String,Integer> orders = new LinkedHashMap<>();
    
    
    
    
    
    /**
     * Creates new form OrderApp
     */
    public OrderApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bologneseCheck = new javax.swing.JCheckBox();
        tboneCheck = new javax.swing.JCheckBox();
        saladCheck = new javax.swing.JCheckBox();
        kefirCheck = new javax.swing.JCheckBox();
        show_orders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Application");

        jLabel1.setText("MENU");

        bologneseCheck.setText("Spaghetti Bolognese = 15 $");

        tboneCheck.setText("T-Bone Steak = 12 $");

        saladCheck.setText("Salad = 5 $");

        kefirCheck.setText("Kefir = 2 $");

        show_orders.setText("Show Orders");
        show_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_ordersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kefirCheck)
                        .addComponent(saladCheck)
                        .addComponent(bologneseCheck)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(show_orders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addComponent(tboneCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bologneseCheck)
                .addGap(18, 18, 18)
                .addComponent(tboneCheck)
                .addGap(18, 18, 18)
                .addComponent(saladCheck)
                .addGap(18, 18, 18)
                .addComponent(kefirCheck)
                .addGap(18, 18, 18)
                .addComponent(show_orders)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showOrders() {
        String message ="";
        int total = 0;
        if (orders.isEmpty()) {
            message = "You don't have any orders.";
        }
        else {
            message += "The orders \n";
            
            for (Map.Entry<String,Integer> entry : orders.entrySet()) {
                message += entry.getKey() + "\n";
                total += entry.getValue();
            }
            message += "Total Price : " + total + " $";
        }
        
        JOptionPane.showMessageDialog(this, message);
    }
    private void show_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_ordersActionPerformed
        if (bologneseCheck.isSelected()) {
            orders.put("Spaghetti Bolognese", 15);
        }
        else {
            orders.remove("Spaghetti Bolognese");
        }
         if (tboneCheck.isSelected()) {
            orders.put("T-Bone Steak", 12);
        }
        else {
            orders.remove("T-Bone Steak");
        }
        if (saladCheck.isSelected()) {
            orders.put("Salad", 5);
        }
        else {
            orders.remove("Salad");
        }
        if (kefirCheck.isSelected()) {
            orders.put("Kefir", 2);
        }
        else {
            orders.remove("Kefir");
        }
        showOrders();

    }//GEN-LAST:event_show_ordersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bologneseCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox kefirCheck;
    private javax.swing.JCheckBox saladCheck;
    private javax.swing.JButton show_orders;
    private javax.swing.JCheckBox tboneCheck;
    // End of variables declaration//GEN-END:variables
}
